CREATE TABLE IF NOT EXISTS GHAS_CID_T (
    ID_INTEGRACAO BIGINT PRIMARY KEY AUTO_INCREMENT,
    IE_INTEGRADO VARCHAR(1),
    DS_LOG TEXT,
    -- Other fields...
);

CREATE TABLE IF NOT EXISTS GHAS_ATEND_PACIENTE_T (
    NR_ATENDIMENTO VARCHAR(255),
    NM_PACIENTE VARCHAR(255),
    DT_NASCIMENTO DATE,
    -- Other fields...
);
